name: gmaxstudiosnetwork
favicon: null
layout_spectrum: 0
typography_spectrum: 0.9568501729518175
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffad01'
    - '#000000'
    - '#6f4c00'
    - '#2f2000'
    - '#c98800'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
